services:
  - type: web
    name: gateway
    runtime: docker
    plan: starter
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: GATEWAY_PORT
        value: ${GATEWAY_PORT}
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
