services:
  - type: web
    name: gateway
    runtime: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: GATEWAY_PORT
        value: ${GATEWAY_PORT}
      - key: DB_HOST
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: order
    runtime: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: ORDER_PORT
        value: ${ORDER_PORT}
      - key: DB_HOST
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: payment
    runtime: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: PAYMENT_PORT
        value: ${PAYMENT_PORT}
      - key: DB_HOST
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: user
    runtime: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: USER_PORT
        value: ${USER_PORT}
      - key: DB_HOST
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: product
    runtime: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildCommand: ""  # Add if needed
    startCommand: ""  # Add if needed
    envVars:
      - key: PRODUCT_PORT
        value: ${PRODUCT_PORT}
      - key: PRODUCT_GRPC_PORT
        value: ${PRODUCT_GRPC_PORT}
      - key: DB_HOST
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
databases:
  - name: db # Required
    postgresMajorVersion: "16"
