basePath: /
definitions:
  ErrorResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  Order:
    properties:
      id:
        type: string
      orderedDate:
        type: string
      productID:
        items:
          type: string
        type: array
      status:
        type: string
      totalPrice:
        type: number
      userID:
        type: string
    type: object
  OrderRequest:
    properties:
      ordered_date:
        description: TotalPrice  float64
        type: string
      product_id:
        items:
          type: string
        type: array
      status:
        type: string
      user_id:
        type: string
    type: object
  Payment:
    properties:
      id:
        type: string
      orderID:
        type: string
      paymentDate:
        type: string
      status:
        type: string
      totalPayment:
        type: number
      userID:
        type: string
    type: object
  PaymentRequest:
    properties:
      order_id:
        type: string
      payment_date:
        type: string
      status:
        type: string
      total_payment:
        type: number
      user_id:
        type: string
    type: object
  Product:
    properties:
      addedAt:
        type: string
      amount:
        type: integer
      category:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  ProductRequest:
    properties:
      added_at:
        type: string
      amount:
        type: integer
      category:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      registrationDate:
        type: string
      role:
        type: string
    type: object
  UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      registration_date:
        type: string
      role:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API Gateway for the E-commerce Microservices project.
  title: E-commerce Microservices API Gateway
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: list all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Order'
            type: array
        "500":
          description: Internal Server Error
      summary: List orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: place an order
      parameters:
      - description: request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: order id
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Place an order
      tags:
      - orders
  /orders/{id}:
    delete:
      consumes:
      - application/json
      description: Delete order by id
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete order
      tags:
      - orders
    get:
      consumes:
      - application/json
      description: Get order by id
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Order'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Update order by id
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Update order
      tags:
      - orders
  /orders/search:
    get:
      consumes:
      - application/json
      description: Search order by user id and status
      parameters:
      - description: user id
        in: query
        name: user
        type: string
      - description: status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Search order
      tags:
      - orders
  /payments:
    get:
      consumes:
      - application/json
      description: list all payments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Payment'
            type: array
        "500":
          description: Internal Server Error
      summary: List payment
      tags:
      - payments
    post:
      consumes:
      - application/json
      description: make a payment
      parameters:
      - description: request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: payment id
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Make payment
      tags:
      - payments
  /payments/{id}:
    delete:
      consumes:
      - application/json
      description: delete a payment
      parameters:
      - description: payment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete payment
      tags:
      - payments
    get:
      consumes:
      - application/json
      description: get a payment
      parameters:
      - description: payment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Payment'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get payment
      tags:
      - payments
    put:
      consumes:
      - application/json
      description: update a payment
      parameters:
      - description: payment id
        in: path
        name: id
        required: true
        type: string
      - description: request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Update payment
      tags:
      - payments
  /payments/search:
    get:
      consumes:
      - application/json
      description: Search payments by user, order, or status
      parameters:
      - description: user id
        in: path
        name: user
        type: string
      - description: order id
        in: path
        name: order
        type: string
      - description: status
        in: path
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Payment'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Search payments
      tags:
      - payments
  /products:
    get:
      consumes:
      - application/json
      description: list all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Product'
            type: array
        "500":
          description: Internal Server Error
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: create product
      parameters:
      - description: Product data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product ID
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Create product
      tags:
      - products
  /products/{id}:
    delete:
      consumes:
      - application/json
      description: delete product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Product'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: update product by id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: update products
      tags:
      - products
  /products/search:
    get:
      consumes:
      - application/json
      description: search product
      parameters:
      - description: Product name
        in: query
        name: name
        type: string
      - description: Product category
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Product'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Search product
      tags:
      - products
  /users:
    get:
      consumes:
      - application/json
      description: list all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/User'
            type: array
        "500":
          description: Internal Server Error
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create a new user
      parameters:
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: user id
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Create user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: delete user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Update user
      tags:
      - users
schemes:
- http
swagger: "2.0"
